AllCops:
  TargetRubyVersion: 2.4.0
  Exclude:
      - 'db/schema.rb'

Metrics/AbcSize:
  Max: 30

Metrics/LineLength:
  Max: 130

Metrics/MethodLength:
  Max: 28

Metrics/ClassLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "db/schema.rb"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
